version: '3'
services:
  app:
    container_name: olx-app
    image: node:18.12.1-alpine
    ports:
      - "5000:5000"
    command: npm install && npm run dev

  mongodb:
    container_name: olx-db
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

networks:
  olx:
    driver: bridge