version: '3'
services:
  app:
    container_name: olx-app
    build: .
    ports:
      - "30202:3000"
    command: npm start

  mongodb:
    container_name: olx-db
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
